In [1]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
age = ['youth', 'youth', 'middle_aged', 'senior', 'senior', 'senior', 'middle_aged', 'youth', 'youth', 'senior', 'youth', 'middle_aged', 'middle_aged', 'senior']
income = ['high', 'high', 'high', 'medium', 'low', 'low', 'low', 'medium', 'low', 'medium', 'medium', 'medium', 'high', 'medium']
student = ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no']
credit_rating = ['fair', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'excellent']
buys_computer = ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']

In [3]:
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string into numbers.
age_encoded=le.fit_transform(age)
income_encoded=le.fit_transform(income)
student_encoded=le.fit_transform(student)
credit_rating_encoded=le.fit_transform(credit_rating)
buys_computer_encoded=le.fit_transform(buys_computer)


In [4]:
features=list(zip(age_encoded,income_encoded,student_encoded,credit_rating_encoded))

In [5]:
from sklearn.model_selection import train_test_split
features_train, features_test,label_train,label_test=train_test_split(features, buys_computer_encoded, test_size=0.2, random_state=42)

In [6]:
model = GaussianNB()

In [7]:
model.fit(features_train, label_train)

GaussianNB()

In [8]:
predicted = model.predict(features_test)
print("Prediction:", predicted)

Prediction: [1 1 1]


In [9]:
conf_mat = confusion_matrix(label_test, predicted)
print("Confusion Matrix:")
print(conf_mat)

Confusion Matrix:
[[0 1]
 [0 2]]


In [10]:
accuracy = accuracy_score(label_test, predicted)
print("Accuracy:", accuracy)

Accuracy: 0.6666666666666666


In [11]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

In [12]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']
temperature=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [13]:
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string into numbers.
weather_encoded=le.fit_transform(weather)
temperature_encoded=le.fit_transform(temperature)
play_encoded=le.fit_transform(play)

In [14]:
features=list(zip(weather_encoded,temperature_encoded))

In [15]:
from sklearn.model_selection import train_test_split
features_train, features_test,label_train,label_test=train_test_split(features, play_encoded, test_size=0.2, random_state=42)

In [16]:
model = GaussianNB()

In [17]:
model.fit(features_train, label_train)

GaussianNB()

In [18]:
predicted = model.predict(features_test)
print("Prediction:", predicted)

Prediction: [0 1 0]


In [19]:
conf_mat = confusion_matrix(label_test, predicted)
print("Confusion Matrix:")
print(conf_mat)
accuracy = accuracy_score(label_test, predicted)
print("Accuracy:", accuracy)

Confusion Matrix:
[[1 0]
 [1 1]]
Accuracy: 0.6666666666666666


In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.naive_bayes import GaussianNB  
from sklearn.metrics import confusion_matrix, accuracy_score

In [21]:

data = {
    'Name of Country': ['China', 'US', 'India', 'Japan', 'Germany', 'Brazil', 'Indonesia', 'Russia', 'UK', 'France'],
    'Country_wise_plastic_waste': [59.05, 42.02, 26.33, 7.99, 6.28, 5.96, 5.85, 5.84, 5.03, 4.98],
    'Main_source': ['Packaging_Industrial', 'Packaging_consumer', 'Consumer_goods', 'Packaging_Electronics', 
                    'Automotive_Packaging', 'Consumer_Packaging', 'Food_Packaging', 'Industrial_Consumer', 
                    'Packaging_consumer', 'Packaging_consumer'],
    'Recycling_Rate': [29.8, 32.1, 11.5, 84.8, 56.1, 1.2, 11.8, 5.6, 46.2, 27.3],
    'Per_capital_waste': [41.2, 127.5, 19.3, 63.2, 75.6, 28.1, 21.3, 40.2, 74.3, 73.1],
    'Coastal_Waste': ['High', 'Medium', 'High', 'Medium', 'Low', 'Medium', 'Very_High', 'Medium', 'Low', 'Low']
}

df = pd.DataFrame(data)

In [22]:
le = LabelEncoder()
df['Main_source'] = le.fit_transform(df['Main_source'])
df['Coastal_Waste'] = le.fit_transform(df['Coastal_Waste'])

In [23]:
X = df[['Country_wise_plastic_waste', 'Main_source', 'Recycling_Rate', 'Per_capital_waste']]
y = df['Coastal_Waste']

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [26]:
gnb = GaussianNB()  
gnb.fit(X_train, y_train)

GaussianNB()

In [27]:
y_pred = gnb.predict(X_test)


In [28]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)

y_pred_labels = le.inverse_transform(y_pred)
print("Predicted Coastal Waste Categories:", y_pred_labels)

Accuracy: 0.5
Confusion Matrix:
 [[0 0 0]
 [0 1 0]
 [1 0 0]]
Predicted Coastal Waste Categories: ['Low' 'High']
